### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [kcousot/rbpi#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by kcousot** [comment]
Done : kcousot/rbpi@9fa61a095c857cbd0b4d66d26a7c177ea9a7ca4e

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/794
